посилання на colab -> https://colab.research.google.com/drive/1SnIcVHTjuwZ5e_HDxO60pvhECflxg10W?usp=sharing

варіант 1

In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
v_1 = np.arange(1, 11)
print("Перші 10 натуральних чисел:", v_1)

Перші 10 натуральних чисел: [ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [3]:
m2 = np.ones((4, 4))
print(m2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 5 та виведіть його значення

In [4]:
m3 = np.random.randint(1, 6, size=(4, 4))
print(m3)

[[2 2 1 4]
 [2 4 3 1]
 [5 3 5 4]
 [3 4 5 3]]


4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення

In [5]:
m4 = np.random.uniform(0, 1, size=(3, 3))
print(m4)

[[0.45856546 0.80019755 0.31653261]
 [0.7663126  0.14878622 0.0114248 ]
 [0.76363715 0.82044163 0.16824452]]


5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення

In [6]:
a5_1 = np.random.randint(1, 21, size=6)
a5_2 = np.random.randint(1, 21, size=6)
print("Array 1:", a5_1)
print("Array 2:", a5_2)
print("Сума:", a5_1 + a5_2)
print("Різниця:", a5_1 - a5_2)
print("Множення (поелементне):", a5_1 * a5_2)

Array 1: [ 2  4 17 11 19  1]
Array 2: [10  6 10  1 18 16]
Сума: [12 10 27 12 37 17]
Різниця: [ -8  -2   7  10   1 -15]
Множення (поелементне): [ 20  24 170  11 342  16]


6. Створіть дві матриці 2x2, заповніть їх довільними цілими числами та знайдіть їх добуток

In [7]:
m6_1 = np.random.randint(1, 10, size=(2, 2))
m6_2 = np.random.randint(1, 10, size=(2, 2))
print("Matrix 1:\n", m6_1)
print("Matrix 2:\n", m6_2)
print("Матричний добуток:\n", np.dot(m6_1, m6_2))

Matrix 1:
 [[9 2]
 [5 7]]
Matrix 2:
 [[2 2]
 [9 7]]
Матричний добуток:
 [[36 32]
 [73 59]]


7. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою

In [8]:
m7_1 = np.random.randint(1, 11, size=(3, 2))
m7_2 = np.random.randint(1, 11, size=(2, 4))
print("Matrix 1:\n", m7_1)
print("Matrix 2:\n", m7_2)
print("Добуток (3x2 * 2x4):\n", np.dot(m7_1, m7_2))

Matrix 1:
 [[10  4]
 [ 6 10]
 [ 4 10]]
Matrix 2:
 [[ 3 10  2  6]
 [ 5  5  2  4]]
Добуток (3x2 * 2x4):
 [[ 50 120  28  76]
 [ 68 110  32  76]
 [ 62  90  28  64]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [9]:
m8 = np.random.randint(1, 8, size=(2, 2))
print("Матриця:\n", m8)

m8_inv = np.linalg.inv(m8)
print("Обернена матриця:\n", m8_inv)

Матриця:
 [[5 4]
 [4 2]]
Обернена матриця:
 [[-0.33333333  0.66666667]
 [ 0.66666667 -0.83333333]]


9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
m9 = np.random.uniform(0, 1, size=(3, 3))
print("Матриця:\n", m9)
print("Транспонована:\n", m9.T)

Матриця:
 [[0.61943288 0.81780799 0.67911564]
 [0.16003162 0.7450367  0.74436597]
 [0.46892299 0.819025   0.51168402]]
Транспонована:
 [[0.61943288 0.16003162 0.46892299]
 [0.81780799 0.7450367  0.819025  ]
 [0.67911564 0.74436597 0.51168402]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.

In [11]:
m10 = np.random.randint(1, 11, size=(3, 4))
v10 = np.random.randint(1, 11, size=(4, 1))
print("Матриця 3x4:\n", m10)
print("Вектор 4x1:\n", v10)
print("Добуток:\n", m10 @ v10)

Матриця 3x4:
 [[ 3 10  9  9]
 [ 9  1  4  8]
 [ 8  9  4  1]]
Вектор 4x1:
 [[3]
 [2]
 [7]
 [6]]
Добуток:
 [[146]
 [105]
 [ 76]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор

In [12]:
m11 = np.random.randint(1, 11, size=(2, 3))
v11 = np.random.randint(1, 11, size=(3, 1))
print("Матриця 2x3:\n", m11)
print("Вектор 3x1:\n", v11)
print("Добуток:\n", m11 @ v11)

Матриця 2x3:
 [[ 6  7  2]
 [10  4  7]]
Вектор 3x1:
 [[5]
 [8]
 [1]]
Добуток:
 [[88]
 [89]]


12.  Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

In [13]:
m12_1 = np.random.randint(1, 11, size=(2, 2))
m12_2 = np.random.randint(1, 11, size=(2, 2))
print("Матриця 1:\n", m12_1)
print("Матриця 2:\n", m12_2)
print("Сума матриць:\n", m12_1 + m12_2)

Матриця 1:
 [[ 3 10]
 [ 9  5]]
Матриця 2:
 [[6 8]
 [1 8]]
Сума матриць:
 [[ 9 18]
 [10 13]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть їх добуток.

In [14]:
m13_1 = np.random.uniform(0, 1, size=(2, 2))
m13_2 = np.random.uniform(0, 1, size=(2, 2))
print("Матриця 1:\n", m13_1)
print("Матриця 2:\n", m13_2)
print("Матричний добуток:\n", m13_1 @ m13_2)

Матриця 1:
 [[0.15485055 0.86328368]
 [0.83937903 0.2792272 ]]
Матриця 2:
 [[0.08307475 0.7793768 ]
 [0.06566122 0.04793338]]
Матричний добуток:
 [[0.06954843 0.16206703]
 [0.0880656  0.66757684]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму елементів матриці.

In [16]:
m14 = np.random.uniform(0, 1, size=(5, 5))
print("Матриця:\n", m14)
print("Сума всіх елементів:", m14.sum())

Матриця:
 [[0.67335715 0.40439165 0.36800946 0.19682091 0.24472346]
 [0.80167516 0.72879322 0.40937143 0.55555781 0.18671456]
 [0.50136107 0.18951201 0.76291875 0.65978657 0.67614067]
 [0.19673519 0.28163291 0.60648034 0.7264864  0.56866374]
 [0.71128818 0.57788776 0.30696872 0.62069176 0.7223252 ]]
Сума всіх елементів: 12.678294063456594


15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці

In [18]:
m15 = np.random.uniform(-1, 1, size=(3, 3))
print("Матриця:\n", m15)
row_sums = m15.sum(axis=1).reshape(-1, 1)
print("Вектор-стовпчик сум рядків:\n", row_sums)

Матриця:
 [[-0.71419872 -0.55738025  0.99059392]
 [-0.53633622  0.62724234 -0.52920918]
 [-0.52411429 -0.30044614  0.60322953]]
Вектор-стовпчик сум рядків:
 [[-0.28098505]
 [-0.43830305]
 [-0.2213309 ]]


ВИСНОВКИ. <br> У ході виконання лабораторної роботи мною було вивчені основи бібліотеки NumPy. Завдяки прикладів, навчились створювати одновимірні та багатовимірні масиви (вектори та матриці), заповнювати їх випадковими числами, виконувати арифметичні операції, транспонування, знаходження оберненої матриці та матричне множення.